#!/bin/bash

echo "Setting up Aethrix Contact Form Database..."
echo ""
echo "✅ GOOD NEWS: Your database table already exists!"
echo ""
echo "If you need to update the policies, run this SQL in your Supabase SQL Editor:"
echo ""
echo "================== UPDATE POLICIES =================="
cat supabase/migrations/001_create_contact_submissions.sql
echo ""
echo "===================================================="
echo ""
echo "🎉 Your contact form is ready to use!"
echo ""
echo "Admin Dashboard Access:"
echo "- Keyboard Shortcut: Ctrl+Alt+Shift+A"
echo "- Password: Osman@123"
echo ""
echo "The form will now save to your Supabase database instead of local storage."
echo ""
echo "🚀 Test it now:"
echo "1. Go to http://localhost:8080/consultation"
echo "2. Fill out the contact form"
echo "3. Press Ctrl+Alt+Shift+A to view submissions"
